apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  name: hello-agones
spec:
  ports:
    - name: default
      containerPort: 7654
  template:
    spec:
      containers:
        - name: hello-agones
          image: shikanime/hello-agones
          imagePullPolicy: Never
