apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: hello-agones
  app.kubernetes.io/instance: hello-agones
  app.kubernetes.io/version: "0.1.0"
  app.kubernetes.io/component: application
resources:
  - gameserver.yaml