apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: hello-agones
build:
  artifacts:
    - image: shikanime/hello-agones
      docker:
        dockerfile: examples/hello_agones/Dockerfile
      context: ../../
deploy:
  kubectl:
    manifests:
      - manifests/gameserver.yaml
portForward:
  - resourceType: pod
    resourceName: hello-agones
    port: 7654