apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: hello-agones
build:
  local:
    useBuildkit: true
  artifacts:
    - image: shikanime/hello-agones
      docker:
        dockerfile: examples/hello_agones/Dockerfile
      context: ../../
deploy:
  kustomize:
    paths:
      - manifests
portForward:
  - resourceType: pod
    resourceName: hello-agones
    port: 7654
